# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, nodejs, stdenv, fetchurl, writeText, git, cacert, writeShellApplication }:
{ src, overrideAttrs ? null, ... } @ args:

let

  yarnPath = ./.yarn/releases/yarn-3.2.3.cjs;
  lockfile = ./yarn.lock;
  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    npm_config_build_from_source = "true";
    # Defines the shell alias to run Yarn.
    postHook = ''
      yarn() {
        CI=1 node "${yarnPath}" "$@"
      }
    '';
  };

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup
      cd "$src"
      HOME="$TMP" yarn_cache_folder="$TMP" CI=1 \
        node '${yarnPath}' nixify fetch-one $locator
      # Because we change the cache dir, Yarn may generate a different name.
      mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit src builder locator;
    name = lib.strings.sanitizeDerivationName locator;
    buildInputs = [ nodejs git cacert ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeText "collect-cache.sh" (lib.concatMapStrings (drv: ''
      cp ${drv} '${drv.outputFilename}'
    '') drvs);


  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "superstar-checkin";
    # Disable Nixify plugin to save on some unnecessary processing.
    yarn_enable_nixify = "false";

    configurePhase = ''
      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure



      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p "$out/libexec/$name" "$out/bin"

      # Move the package contents to the output directory.
      # - If the package.json has a `files` field, only files matching those patterns are copied
      # - Otherwise all files are copied
      yarn pack --out package.tgz
      tar xzvf package.tgz --directory "$out/libexec/$name" --strip-components=1

      cp .yarnrc* "$out/libexec/$name"
      cp --recursive .yarn "$out/libexec/$name"

      # If the project uses the node-modules linker, then
      # include the node_modules folder in the package.
      if [ -d node_modules ]; then
        cp --recursive node_modules "$out/libexec/$name"
      fi

      cd "$out/libexec/$name"

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $out/bin

      # A package with node_modules doesn't need the cache
      if [ -d node_modules ]; then
        yarn cache clean
      fi

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
      yarn = writeShellApplication {
        name = "yarn";
        runtimeInputs = [ nodejs ];
        text = ''
          ${yarnPath} --cwd ${project}/libexec/${project.name} "$@"
        '';
      };
    };
  });

cacheEntries = {
"@types/node@npm:18.7.18" = { filename = "@types-node-npm-18.7.18-5bcc3f839f-8aec61f0f9.zip"; sha512 = "8aec61f0f96e2a69ce51f1f40f949ca578bbb4fe05d7c0b8ce3aeeb848e90f755837f17f6ac132ca404d974fe9b2974150ad3b4984fc9dc7c3ceddb10bae0167"; };
"tsc@npm:2.0.4" = { filename = "tsc-npm-2.0.4-e331b066cb-50b1024088.zip"; sha512 = "50b10240887424c66454687f0fca4e319713b35cb44f0dab228719eb4dd757251f83c3d79e60d29dfbe90c2d6f1272f793b83e75a9fca2c622b4213ad3eb8cb1"; };
"yaml@npm:2.1.1" = { filename = "yaml-npm-2.1.1-e717f9b915-f48bb20991.zip"; sha512 = "f48bb209918aa57cfaf78ef6448d1a1f8187f45c746f933268b7023dc59e5456004611879126c9bb5ea55b0a2b1c2b392dfde436931ece0c703a3d754562bb96"; };
"typescript@npm:4.8.3" = { filename = "typescript-npm-4.8.3-7c28a78612-8286a5edca.zip"; sha512 = "8286a5edcaf3d68e65c451aa1e7150ad1cf53ee0813c07ec35b7abdfdb10f355ecaa13c6a226a694ae7a67785fd7eeebf89f845da0b4f7e4a35561ddc459aba0"; };
"axios-cookiejar-support@npm:4.0.3" = { filename = "axios-cookiejar-support-npm-4.0.3-9dc869865b-e2f678b0a1.zip"; sha512 = "e2f678b0a1e03d53dda1ba24fe06baf5929f4e05d5c2eea3922a082bfec7ed4c3036a5cadddda6e1228b8a712351fd1c71435bcf89e657f5a75a6468703e96c1"; };
"axios@npm:0.27.2" = { filename = "axios-npm-0.27.2-dbe3a48aea-38cb754046.zip"; sha512 = "38cb7540465fe8c4102850c4368053c21683af85c5fdf0ea619f9628abbcb59415d1e22ebc8a6390d2bbc9b58a9806c874f139767389c862ec9b772235f06854"; };
"chalk@npm:4.1.2" = { filename = "chalk-npm-4.1.2-ba8b67ab80-fe75c9d5c7.zip"; sha512 = "fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc"; };
"@types/jsdom@npm:20.0.0" = { filename = "@types-jsdom-npm-20.0.0-a0c8462a9d-13e67d3134.zip"; sha512 = "13e67d31347e02d46ec6a23919b3ce39d86136665922a2a6cb977e216a2f46c22d2f025d0586a64ab492ebaa5f43da669b6f173a5a8cfd3e3bb7c9d19b6cfa9e"; };
"tough-cookie@npm:4.1.2" = { filename = "tough-cookie-npm-4.1.2-09068826e1-a7359e9a3e.zip"; sha512 = "a7359e9a3e875121a84d6ba40cc184dec5784af84f67f3a56d1d2ae39b87c0e004e6ba7c7331f9622a7d2c88609032473488b28fe9f59a1fec115674589de39a"; };
"oicq@https://github.com/Clansty/oicq.git#commit=6c3f34adc681e73c2511f1f49a79fb387dcd1555" = { filename = "oicq-https-0d6a293443-27932ed34f.zip"; sha512 = "27932ed34fc2fafd6aa6a2f7b4ed361ade6caed98b1b36c465c011f7716240c6c44bec1d8c36f52c878bc1f28df03c485236bd93932cdd462509401471b7be21"; };
"http-cookie-agent@npm:4.0.2" = { filename = "http-cookie-agent-npm-4.0.2-3ceb4d8b3f-864a23c555.zip"; sha512 = "864a23c555d9ccaee4b5dbac7e61a05283aae76d1bbce9c809ed79b0e472da7df496200c1129699ec128c67e8dea7b5a663ada1ae8f11e6ec88461c5b21ab3b9"; };
"follow-redirects@npm:1.15.2" = { filename = "follow-redirects-npm-1.15.2-1ec1dd82be-faa66059b6.zip"; sha512 = "faa66059b66358ba65c234c2f2a37fcec029dc22775f35d9ad6abac56003268baf41e55f9ee645957b32c7d9f62baf1f0b906e68267276f54ec4b4c597c2b190"; };
"tencentcloud-sdk-nodejs@npm:4.0.536" = { filename = "tencentcloud-sdk-nodejs-npm-4.0.536-18cd9d98a0-8fd15711a0.zip"; sha512 = "8fd15711a0ee0ae61f9bf3cbebb5e5705cc2c4ef1f761564754d6ac75d9e6e7318847a12d5a42d1dd9ae7d0be9bb8476bb262bdb96492e4f98d12de08186048a"; };
"@types/tough-cookie@npm:4.0.2" = { filename = "@types-tough-cookie-npm-4.0.2-9e61f877e6-e055556ffd.zip"; sha512 = "e055556ffdaa39ad85ede0af192c93f93f986f4bd9e9426efdc2948e3e2632db3a4a584d4937dbf6d7620527419bc99e6182d3daf2b08685e710f2eda5291905"; };
"ansi-styles@npm:4.3.0" = { filename = "ansi-styles-npm-4.3.0-245c7d42c7-513b44c3b2.zip"; sha512 = "513b44c3b2105dd14cc42a19271e80f386466c4be574bccf60b627432f9198571ebf4ab1e4c3ba17347658f4ee1711c163d574248c0c1cdc2d5917a0ad582ec4"; };
"supports-color@npm:7.2.0" = { filename = "supports-color-npm-7.2.0-606bfcf7da-3dda818de0.zip"; sha512 = "3dda818de06ebbe5b9653e07842d9479f3555ebc77e9a0280caf5a14fb877ffee9ed57007c3b78f5a6324b8dbeec648d9e97a24e2ed9fdb81ddc69ea07100f4a"; };
"cheerio@npm:1.0.0-rc.12" = { filename = "cheerio-npm-1.0.0-rc.12-6785a97c2a-5d4c1b7a53.zip"; sha512 = "5d4c1b7a53cf22d3a2eddc0aff70cf23cbb30d01a4c79013e703a012475c02461aa1fcd99127e8d83a02216386ed6942b2c8103845fd0812300dd199e6e7e054"; };
"parse5@npm:7.1.1" = { filename = "parse5-npm-7.1.1-27fa6524c4-8f72fbfa6d.zip"; sha512 = "8f72fbfa6df83a3f29f58e1818f7bd46b47ff3e26d79c74e10b8fc7ef7ee76163f205113f1b2f6a5b8dc4e31e726f490444f04890cead6e974dbcbe8172b1321"; };
"psl@npm:1.9.0" = { filename = "psl-npm-1.9.0-a546edad1a-20c4277f64.zip"; sha512 = "20c4277f640c93d393130673f392618e9a8044c6c7bf61c53917a0fddb4952790f5f362c6c730a9c32b124813e173733f9895add8d26f566ed0ea0654b2e711d"; };
"punycode@npm:2.1.1" = { filename = "punycode-npm-2.1.1-26eb3e15cf-823bf443c6.zip"; sha512 = "823bf443c6dd14f669984dea25757b37993f67e8d94698996064035edd43bed8a5a17a9f12e439c2b35df1078c6bec05a6c86e336209eb1061e8025c481168e8"; };
"universalify@npm:0.2.0" = { filename = "universalify-npm-0.2.0-9984e61c10-e86134cb12.zip"; sha512 = "e86134cb12919d177c2353196a4cc09981524ee87abf621f7bc8d249dbbbebaec5e7d1314b96061497981350df786e4c5128dbf442eba104d6e765bc260678b5"; };
"form-data@npm:4.0.0" = { filename = "form-data-npm-4.0.0-916facec2d-01135bf867.zip"; sha512 = "01135bf8675f9d5c61ff18e2e2932f719ca4de964e3be90ef4c36aacfc7b9cb2fceb5eca0b7e0190e3383fe51c5b37f4cb80b62ca06a99aaabfcfd6ac7c9328c"; };
"long@npm:4.0.0" = { filename = "long-npm-4.0.0-ecd96a31ed-16afbe8f74.zip"; sha512 = "16afbe8f749c7c849db1f4de4e2e6a31ac6e617cead3bdc4f9605cb703cd20e1e9fc1a7baba674ffcca57d660a6e5b53a9e236d7b25a295d3855cca79cc06744"; };
"pngjs@npm:6.0.0" = { filename = "pngjs-npm-6.0.0-31d8d85681-ab6c285086.zip"; sha512 = "ab6c285086060087097eab9fe6b5a528a24f9e79c03dea2b4fd6264ed4fdb5beff4a3257eeeaf2a9dc18249b539609c2a4e4013c567164a1f6b5ba2c974d5ecb"; };
"get-stream@npm:6.0.1" = { filename = "get-stream-npm-6.0.1-83e51a4642-e04ecece32.zip"; sha512 = "e04ecece32c92eebf5b8c940f51468cd53554dcbb0ea725b2748be583c9523d00128137966afce410b9b051eb2ef16d657cd2b120ca8edafcf5a65e81af63cad"; };
"is-stream@npm:2.0.1" = { filename = "is-stream-npm-2.0.1-c802db55e7-b8e05ccdf9.zip"; sha512 = "b8e05ccdf96ac330ea83c12450304d4a591f9958c11fd17bed240af8d5ffe08aedafa4c0f4cfccd4d28dc9d4d129daca1023633d5c11601a6cbc77521f6fae66"; };
"tslib@npm:1.13.0" = { filename = "tslib-npm-1.13.0-f5e9ea9b66-50e9327361.zip"; sha512 = "50e9327361f94f328c0715582a7f725f69838ab3c2559d143643c5367262fe14552768ba8cfc65bc7dc924a619aea599b3a28b6653458cdca77bbebaf9bc8df4"; };
"url-parse@npm:1.5.10" = { filename = "url-parse-npm-1.5.10-64fa2bcd6d-fbdba6b1d8.zip"; sha512 = "fbdba6b1d83336aca2216bbdc38ba658d9cfb8fc7f665eb8b17852de638ff7d1a162c198a8e4ed66001ddbf6c9888d41e4798912c62b4fd777a31657989f7bdf"; };
"typescript@patch:typescript@npm%3A4.8.3#~builtin<compat/typescript>::version=4.8.3&hash=a1c5e5" = { filename = "typescript-patch-4d824bf818-2222d2382f.zip"; sha512 = "2222d2382fb3146089b1d27ce2b55e9d1f99cc64118f1aba75809b693b856c5d3c324f052f60c75b577947fc538bc1c27bad0eb76cbdba9a63a253489504ba7e"; };
"agent-base@npm:6.0.2" = { filename = "agent-base-npm-6.0.2-428f325a93-f52b6872cc.zip"; sha512 = "f52b6872cc96fd5f622071b71ef200e01c7c4c454ee68bc9accca90c98cfb39f2810e3e9aa330435835eedc8c23f4f8a15267f67c6e245d2b33757575bdac49d"; };
"has-flag@npm:4.0.0" = { filename = "has-flag-npm-4.0.0-32af9f0536-261a135703.zip"; sha512 = "261a1357037ead75e338156b1f9452c016a37dcd3283a972a30d9e4a87441ba372c8b81f818cd0fbcd9c0354b4ae7e18b9e1afa1971164aef6d18c2b6095a8ad"; };
"node-fetch@npm:2.6.9" = { filename = "node-fetch-npm-2.6.9-9fc9a54529-acb04f9ce7.zip"; sha512 = "acb04f9ce7224965b2b59e71b33c639794d8991efd73855b0b250921382b38331ffc9d61bce502571f6cc6e11a8905ca9b1b6d4aeb586ab093e2756a1fd190d0"; };
"entities@npm:4.4.0" = { filename = "entities-npm-4.4.0-97635dc5cc-84d250329f.zip"; sha512 = "84d250329f4b56b40fa93ed067b194db21e8815e4eb9b59f43a086f0ecd342814f6bc483de8a77da5d64e0f626033192b1b4f1792232a7ea6b970ebe0f3187c2"; };
"color-convert@npm:2.0.1" = { filename = "color-convert-npm-2.0.1-79730e935b-79e6bdb9fd.zip"; sha512 = "79e6bdb9fd479a205c71d89574fccfb22bd9053bd98c6c4d870d65c132e5e904e6034978e55b43d69fcaa7433af2016ee203ce76eeba9cfa554b373e7f7db336"; };
"domhandler@npm:5.0.3" = { filename = "domhandler-npm-5.0.3-3ede73dc10-0f58f4a6af.zip"; sha512 = "0f58f4a6af63e6f3a4320aa446d28b5790a009018707bce2859dcb1d21144c7876482b5188395a188dfa974238c019e0a1e610d2fc269a12b2c192ea2b0b131c"; };
"probe-image-size@npm:7.2.3" = { filename = "probe-image-size-npm-7.2.3-2b6ee36e6f-1a5eeb8f5c.zip"; sha512 = "1a5eeb8f5cb979172144a5d7a017c70fcd664ccc8af9ad3a803903ee81864abea4036adae4fc6e66e9ae21bd3ce0febefaf1f32e65a77ff226b2eb61e9e4978c"; };
"https-proxy-agent@npm:5.0.1" = { filename = "https-proxy-agent-npm-5.0.1-42d65f358e-571fccdf38.zip"; sha512 = "571fccdf38184f05943e12d37d6ce38197becdd69e58d03f43637f7fa1269cf303a7d228aa27e5b27bbd3af8f09fd938e1c91dcfefff2df7ba77c20ed8dfc765"; };
"asynckit@npm:0.4.0" = { filename = "asynckit-npm-0.4.0-c718858525-7b78c451df.zip"; sha512 = "7b78c451df768adba04e2d02e63e2d0bf3b07adcd6e42b4cf665cb7ce899bedd344c69a1dcbce355b5f972d597b25aaa1c1742b52cffd9caccb22f348114f6be"; };
"parse5-htmlparser2-tree-adapter@npm:7.0.0" = { filename = "parse5-htmlparser2-tree-adapter-npm-7.0.0-38e1b3a974-fc5d01e077.zip"; sha512 = "fc5d01e07733142a1baf81de5c2a9c41426c04b7ab29dd218acb80cd34a63177c90aff4a4aee66cf9f1d0aeecff1389adb7452ad6f8af0a5888e3e9ad6ef733d"; };
"form-data@npm:3.0.1" = { filename = "form-data-npm-3.0.1-d080d436e0-b019e8d35c.zip"; sha512 = "b019e8d35c8afc14a2bd8a7a92fa4f525a4726b6d5a9740e8d2623c30e308fbb58dc8469f90415a856698933c8479b01646a9dff33c87cc4e76d72aedbbf860d"; };
"ts-node@npm:10.9.1" = { filename = "ts-node-npm-10.9.1-6c268be7f4-090adff130.zip"; sha512 = "090adff1302ab20bd3486e6b4799e90f97726ed39e02b39e566f8ab674fd5bd5f727f43615debbfc580d33c6d9d1c6b1b3ce7d8e3cca3e20530a145ffa232c35"; };
"combined-stream@npm:1.0.8" = { filename = "combined-stream-npm-1.0.8-dc14d4a63a-49fa4aeb49.zip"; sha512 = "49fa4aeb4916567e33ea81d088f6584749fc90c7abec76fd516bf1c5aa5c79f3584b5ba3de6b86d26ddd64bae5329c4c7479343250cfe71c75bb366eae53bb7c"; };
"mime-types@npm:2.1.35" = { filename = "mime-types-npm-2.1.35-dd9ea9f3e2-89a5b7f1de.zip"; sha512 = "89a5b7f1def9f3af5dad6496c5ed50191ae4331cc5389d7c521c8ad28d5fdad2d06fd81baf38fed813dc4e46bb55c8145bb0ff406330818c9cf712fb2e9b3836"; };
"dom-serializer@npm:2.0.0" = { filename = "dom-serializer-npm-2.0.0-378ebc7200-cd1810544f.zip"; sha512 = "cd1810544fd8cdfbd51fa2c0c1128ec3a13ba92f14e61b7650b5de421b88205fd2e3f0cc6ace82f13334114addb90ed1c2f23074a51770a8e9c1273acbc7f3e6"; };
"domutils@npm:3.0.1" = { filename = "domutils-npm-3.0.1-7937818218-23aa7a8405.zip"; sha512 = "23aa7a840572d395220e173cb6263b0d028596e3950100520870a125af33ff819e6f609e1606d6f7d73bd9e7feb03bb404286e57a39063b5384c62b724d987b3"; };
"log4js@npm:6.6.1" = { filename = "log4js-npm-6.6.1-00e7698906-68f29e7b8b.zip"; sha512 = "68f29e7b8b0efa2f987e65ee122fde0bc806dd7ad20f0a9f2da316696423e42381ba348bd6e2f6a2feba042a6ed33c14955210741f47ab897b3204aba8bcd84b"; };
"querystringify@npm:2.2.0" = { filename = "querystringify-npm-2.2.0-4e77c9f606-5641ea231b.zip"; sha512 = "5641ea231bad7ef6d64d9998faca95611ed4b11c2591a8cae741e178a974f6a8e0ebde008475259abe1621cb15e692404e6b6626e927f7b849d5c09392604b15"; };
"requires-port@npm:1.0.0" = { filename = "requires-port-npm-1.0.0-fd036b488a-eee0e303ad.zip"; sha512 = "eee0e303adffb69be55d1a214e415cf42b7441ae858c76dfc5353148644f6fd6e698926fc4643f510d5c126d12a705e7c8ed7e38061113bdf37547ab356797ff"; };
"htmlparser2@npm:8.0.1" = { filename = "htmlparser2-npm-8.0.1-b432299617-06d5c71e83.zip"; sha512 = "06d5c71e8313597722bc429ae2a7a8333d77bd3ab07ccb916628384b37332027b047f8619448d8f4a3312b6609c6ea3302a4e77435d859e9e686999e6699ca39"; };
"debug@npm:4.3.4" = { filename = "debug-npm-4.3.4-4513954577-3dbad3f94e.zip"; sha512 = "3dbad3f94ea64f34431a9cbf0bafb61853eda57bff2880036153438f50fb5a84f27683ba0d8e5426bf41a8c6ff03879488120cf5b3a761e77953169c0600a708"; };
"color-name@npm:1.1.4" = { filename = "color-name-npm-1.1.4-025792b0ea-b044585952.zip"; sha512 = "b0445859521eb4021cd0fb0cc1a75cecf67fceecae89b63f62b201cca8d345baf8b952c966862a9d9a2632987d4f6581f0ec8d957dfacece86f0a7919316f610"; };
"domelementtype@npm:2.3.0" = { filename = "domelementtype-npm-2.3.0-02de7cbfba-ee837a318f.zip"; sha512 = "ee837a318ff702622f383409d1f5b25dd1024b692ef64d3096ff702e26339f8e345820f29a68bcdcea8cfee3531776b3382651232fbeae95612d6f0a75efb4f6"; };
"lodash.merge@npm:4.6.2" = { filename = "lodash.merge-npm-4.6.2-77cb4416bf-ad580b4bdb.zip"; sha512 = "ad580b4bdbb7ca1f7abf7e1bce63a9a0b98e370cf40194b03380a46b4ed799c9573029599caebc1b14e3f24b111aef72b96674a56cfa105e0f5ac70546cdc005"; };
"cheerio-select@npm:2.1.0" = { filename = "cheerio-select-npm-2.1.0-e92bc2f296-843d6d4799.zip"; sha512 = "843d6d479922f28a6c5342c935aff1347491156814de63c585a6eb73baf7bb4185c1b4383a1195dca0f12e3946d737c7763bcef0b9544c515d905c5c44c5308b"; };
"stream-parser@npm:0.3.1" = { filename = "stream-parser-npm-0.3.1-0b70187c85-4d86ff8cff.zip"; sha512 = "4d86ff8cffe7c7587dc91433fff9dce38a93ea7e9f47560055addc81eae6b6befab22b75643ce539faf325fe2b17d371778242566bed086e75f6cffb1e76c06c"; };
"whatwg-url@npm:5.0.0" = { filename = "whatwg-url-npm-5.0.0-374fb45e60-b8daed4ad3.zip"; sha512 = "b8daed4ad3356cc4899048a15b2c143a9aed0dfae1f611ebd55073310c7b910f522ad75d727346ad64203d7e6c79ef25eafd465f4d12775ca44b90fa82ed9e2c"; };
"@tsconfig/node10@npm:1.0.9" = { filename = "@tsconfig-node10-npm-1.0.9-f2e2d20feb-a33ae4dc2a.zip"; sha512 = "a33ae4dc2a621c0678ac8ac4bceb8e512ae75dac65417a2ad9b022d9b5411e863c4c198b6ba9ef659e14b9fb609bbec680841a2e84c1172df7a5ffcf076539df"; };
"@tsconfig/node12@npm:1.0.11" = { filename = "@tsconfig-node12-npm-1.0.11-9710d1c61b-5ce29a41b1.zip"; sha512 = "5ce29a41b13e7897a58b8e2df11269c5395999e588b9a467386f99d1d26f6c77d1af2719e407621412520ea30517d718d5192a32403b8dfcc163bf33e40a338a"; };
"@tsconfig/node14@npm:1.0.3" = { filename = "@tsconfig-node14-npm-1.0.3-15321421d2-19275fe80c.zip"; sha512 = "19275fe80c4c8d0ad0abed6a96dbf00642e88b220b090418609c4376e1cef81bf16237bf170ad1b341452feddb8115d8dd2e5acdfdea1b27422071163dc9ba9d"; };
"@tsconfig/node16@npm:1.0.3" = { filename = "@tsconfig-node16-npm-1.0.3-6a4a30eda2-3a8b657dd0.zip"; sha512 = "3a8b657dd047495b7ad23437d6afd20297ce90380ff0bdee93fc7d39a900dbd8d9e26e53ff6b465e7967ce2adf0b218782590ce9013285121e6a5928fbd6819f"; };
"acorn-walk@npm:8.2.0" = { filename = "acorn-walk-npm-8.2.0-2f2cac3177-1715e76c01.zip"; sha512 = "1715e76c01dd7b2d4ca472f9c58968516a4899378a63ad5b6c2d668bba8da21a71976c14ec5f5b75f887b6317c4ae0b897ab141c831d741dc76024d8745f1ad1"; };
"acorn@npm:8.8.0" = { filename = "acorn-npm-8.8.0-9ef399ab45-7270ca82b2.zip"; sha512 = "7270ca82b242eafe5687a11fea6e088c960af712683756abf0791b68855ea9cace3057bd5e998ffcef50c944810c1e0ca1da526d02b32110e13c722aa959afdc"; };
"arg@npm:4.1.3" = { filename = "arg-npm-4.1.3-1748b966a8-544af8dd3f.zip"; sha512 = "544af8dd3f60546d3e4aff084d451b96961d2267d668670199692f8d054f0415d86fc5497d0e641e91546f0aa920e7c29e5250e99fc89f5552a34b5d93b77f43"; };
"create-require@npm:1.1.1" = { filename = "create-require-npm-1.1.1-839884ca2e-a9a1503d43.zip"; sha512 = "a9a1503d4390d8b59ad86f4607de7870b39cad43d929813599a23714831e81c520bddf61bcdd1f8e30f05fd3a2b71ae8538e946eb2786dc65c2bbc520f692eff"; };
"diff@npm:4.0.2" = { filename = "diff-npm-4.0.2-73133c7102-f2c09b0ce4.zip"; sha512 = "f2c09b0ce4e6b301c221addd83bf3f454c0bc00caa3dd837cf6c127d6edf7223aa2bbe3b688feea110b7f262adbfc845b757c44c8a9f8c0c5b15d8fa9ce9d20d"; };
"make-error@npm:1.3.6" = { filename = "make-error-npm-1.3.6-ccb85d9458-b86e5e0e25.zip"; sha512 = "b86e5e0e25f7f777b77fabd8e2cbf15737972869d852a22b7e73c17623928fccb826d8e46b9951501d3f20e51ad74ba8c59ed584f610526a48f8ccf88aaec402"; };
"v8-compile-cache-lib@npm:3.0.1" = { filename = "v8-compile-cache-lib-npm-3.0.1-4886071ece-78089ad549.zip"; sha512 = "78089ad549e21bcdbfca10c08850022b22024cdcc2da9b168bcf5a73a6ed7bf01a9cebb9eac28e03cd23a684d81e0502797e88f3ccd27a32aeab1cfc44c39da0"; };
"yn@npm:3.1.1" = { filename = "yn-npm-3.1.1-8ad4259784-2c487b0e14.zip"; sha512 = "2c487b0e149e746ef48cda9f8bad10fc83693cd69d7f9dcd8be4214e985de33a29c9e24f3c0d6bcf2288427040a8947406ab27f7af67ee9456e6b84854f02dd6"; };
"delayed-stream@npm:1.0.0" = { filename = "delayed-stream-npm-1.0.0-c5a4c4cc02-46fe6e83e2.zip"; sha512 = "46fe6e83e2cb1d85ba50bd52803c68be9bd953282fa7096f51fc29edd5d67ff84ff753c51966061e5ba7cb5e47ef6d36a91924eddb7f3f3483b1c560f77a0020"; };
"mime-db@npm:1.52.0" = { filename = "mime-db-npm-1.52.0-b5371d6fd2-0d99a03585.zip"; sha512 = "0d99a03585f8b39d68182803b12ac601d9c01abfa28ec56204fa330bc9f3d1c5e14beb049bafadb3dbdf646dfb94b87e24d4ec7b31b7279ef906a8ea9b6a513f"; };
"date-format@npm:4.0.13" = { filename = "date-format-npm-4.0.13-64e384acc1-b4584fdd43.zip"; sha512 = "b4584fdd43d31e9c900da775cce4806903ba207e21f79d99959858141849d41ec919f941d1fb2e4efd2355ce1909ca1fe41a5184568c74cb540cf24c4f8bb39b"; };
"flatted@npm:3.2.7" = { filename = "flatted-npm-3.2.7-0da10b7c56-427633049d.zip"; sha512 = "427633049d55bdb80201c68f7eb1cbd533e03eac541f97d3aecab8c5526f12a20ccecaeede08b57503e772c769e7f8680b37e8d482d1e5f8d7e2194687f9ea35"; };
"rfdc@npm:1.3.0" = { filename = "rfdc-npm-1.3.0-272f288ad8-fb2ba8512e.zip"; sha512 = "fb2ba8512e43519983b4c61bd3fa77c0f410eff6bae68b08614437bc3f35f91362215f7b4a73cbda6f67330b5746ce07db5dd9850ad3edc91271ad6deea0df32"; };
"@cspotcode/source-map-support@npm:0.8.1" = { filename = "@cspotcode-source-map-support-npm-0.8.1-964f2de99d-5718f26708.zip"; sha512 = "5718f267085ed8edb3e7ef210137241775e607ee18b77d95aa5bd7514f47f5019aa2d82d96b3bf342ef7aa890a346fa1044532ff7cc3009e7d24fce3ce6200fa"; };
"needle@npm:2.9.1" = { filename = "needle-npm-2.9.1-f40e591726-746ae3a378.zip"; sha512 = "746ae3a3782f0a057ff304a98843cc6f2009f978a0fad0c3e641a9d46d0b5702bb3e197ba08aecd48678067874a991c4f5fc320c7e51a4c041d9dd3441146cf0"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"boolbase@npm:1.0.0" = { filename = "boolbase-npm-1.0.0-965fe9af6d-3e25c80ef6.zip"; sha512 = "3e25c80ef626c3a3487c73dbfc70ac322ec830666c9ad915d11b701142fab25ec1e63eff2c450c74347acfd2de854ccde865cd79ef4db1683f7c7b046ea43bb0"; };
"css-what@npm:6.1.0" = { filename = "css-what-npm-6.1.0-57f751efbb-b975e547e1.zip"; sha512 = "b975e547e1e90b79625918f84e67db5d33d896e6de846c9b584094e529f0c63e2ab85ee33b9daffd05bff3a146a1916bec664e18bb76dd5f66cbff9fc13b2bbe"; };
"streamroller@npm:3.1.2" = { filename = "streamroller-npm-3.1.2-56c1517978-4215bf57fe.zip"; sha512 = "4215bf57fe80c583ba200075f9a62b9be9a3d7491201905bf7b5a09d7e87903a47f7c62b1ce0fd2161dbd497cac41068e8f48dda0f9bfceb084487de5798f043"; };
"tr46@npm:0.0.3" = { filename = "tr46-npm-0.0.3-de53018915-726321c5ea.zip"; sha512 = "726321c5eaf41b5002e17ffbd1fb7245999a073e8979085dacd47c4b4e8068ff5777142fc6726d6ca1fd2ff16921b48788b87225cbc57c72636f6efa8efbffe3"; };
"webidl-conversions@npm:3.0.1" = { filename = "webidl-conversions-npm-3.0.1-60310f6a2b-c92a0a6ab9.zip"; sha512 = "c92a0a6ab95314bde9c32e1d0a6dfac83b578f8fa5f21e675bc2706ed6981bc26b7eb7e6a1fab158e5ce4adf9caa4a0aee49a52505d4d13c7be545f15021b17c"; };
"debug@npm:2.6.9" = { filename = "debug-npm-2.6.9-7d4cb597dc-d2f51589ca.zip"; sha512 = "d2f51589ca66df60bf36e1fa6e4386b318c3f1e06772280eea5b1ae9fd3d05e9c2b7fd8a7d862457d00853c75b00451aa2d7459b924629ee385287a650f58fe6"; };
"sax@npm:1.2.4" = { filename = "sax-npm-1.2.4-178f05f12f-d3df7d32b8.zip"; sha512 = "d3df7d32b897a2c2f28e941f732c71ba90e27c24f62ee918bd4d9a8cfb3553f2f81e5493c7f0be94a11c1911b643a9108f231dd6f60df3fa9586b5d2e3e9e1fe"; };
"debug@npm:3.2.7" = { filename = "debug-npm-3.2.7-754e818c7a-b3d8c59407.zip"; sha512 = "b3d8c5940799914d30314b7c3304a43305fd0715581a919dacb8b3176d024a782062368405b47491516d2091d6462d4d11f2f4974a405048094f8bfebfa3071c"; };
"iconv-lite@npm:0.4.24" = { filename = "iconv-lite-npm-0.4.24-c5c4ac6695-bd9f120f5a.zip"; sha512 = "bd9f120f5a5b306f0bc0b9ae1edeb1577161503f5f8252a20f1a9e56ef8775c9959fd01c55f2d3a39d9a8abaf3e30c1abeb1895f367dcbbe0a8fd1c9ca01c4f6"; };
"@jridgewell/trace-mapping@npm:0.3.9" = { filename = "@jridgewell-trace-mapping-npm-0.3.9-91625cd7fb-d89597752f.zip"; sha512 = "d89597752fd88d3f3480845691a05a44bd21faac18e2185b6f436c3b0fd0c5a859fbbd9aaa92050c4052caf325ad3e10e2e1d1b64327517471b7d51babc0ddef"; };
"css-select@npm:5.1.0" = { filename = "css-select-npm-5.1.0-9365a79de5-2772c049b1.zip"; sha512 = "2772c049b188d3b8a8159907192e926e11824aea525b8282981f72ba3f349cf9ecd523fdf7734875ee2cb772246c22117fc062da105b6d59afe8dcd5c99c9bda"; };
"ms@npm:2.0.0" = { filename = "ms-npm-2.0.0-9e1101a471-0e6a22b8b7.zip"; sha512 = "0e6a22b8b746d2e0b65a430519934fefd41b6db0682e3477c10f60c76e947c4c0ad06f63ffdf1d78d335f83edee8c0aa928aa66a36c7cd95b69b26f468d527f4"; };
"jsdom@npm:20.0.0" = { filename = "jsdom-npm-20.0.0-9c1ad43ab8-f69b40679d.zip"; sha512 = "f69b40679d8cfaee2353615445aaff08b823c53dc7778ede6592d02ed12b3e9fb4e8db2b6d033551b67e08424a3adb2b79d231caa7dcda2d16019c20c705c11f"; };
"fs-extra@npm:8.1.0" = { filename = "fs-extra-npm-8.1.0-197473387f-bf44f0e6ce.zip"; sha512 = "bf44f0e6cea59d5ce071bba4c43ca76d216f89e402dc6285c128abc0902e9b8525135aa808adad72c9d5d218e9f4bcc63962815529ff2f684ad532172a284880"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
"@jridgewell/resolve-uri@npm:3.1.0" = { filename = "@jridgewell-resolve-uri-npm-3.1.0-6ff2351e61-b5ceaaf9a1.zip"; sha512 = "b5ceaaf9a110fcb2780d1d8f8d4a0bfd216702f31c988d8042e5f8fbe353c55d9b0f55a1733afdc64806f8e79c485d2464680ac48a0d9fcadb9548ee6b81d267"; };
"@jridgewell/sourcemap-codec@npm:1.4.14" = { filename = "@jridgewell-sourcemap-codec-npm-1.4.14-f5f0630788-61100637b6.zip"; sha512 = "61100637b6d173d3ba786a5dff019e1a74b1f394f323c1fee337ff390239f053b87266c7a948777f4b1ee68c01a8ad0ab61e5ff4abb5a012a0b091bec391ab97"; };
"nth-check@npm:2.1.1" = { filename = "nth-check-npm-2.1.1-f97afc8169-5afc3dafcd.zip"; sha512 = "5afc3dafcd1573b08877ca8e6148c52abd565f1d06b1eb08caf982e3fa289a82f2cae697ffb55b5021e146d60443f1590a5d6b944844e944714a5b549675bcd3"; };
"abab@npm:2.0.6" = { filename = "abab-npm-2.0.6-2662fba7f0-6ffc1af4ff.zip"; sha512 = "6ffc1af4ff315066c62600123990d87551ceb0aafa01e6539da77b0f5987ac7019466780bf480f1787576d4385e3690c81ccc37cfda12819bf510b8ab47e5a3e"; };
"cssom@npm:0.5.0" = { filename = "cssom-npm-0.5.0-44ab2704f2-823471aa30.zip"; sha512 = "823471aa30091c59e0a305927c30e7768939b6af70405808f8d2ce1ca778cddcb24722717392438329d1691f9a87cb0183b64b8d779b56a961546d54854fde01"; };
"decimal.js@npm:10.4.0" = { filename = "decimal.js-npm-10.4.0-9a246fb0fa-98702d9d81.zip"; sha512 = "98702d9d817a9e5b3767ea6580e7f3b35544b9454e463a5dd5d3232131470f39067d02864c45cab009eb1200bc162cd26a33d34c622cd79e4657a3e25e95fb4e"; };
"is-potential-custom-element-name@npm:1.0.1" = { filename = "is-potential-custom-element-name-npm-1.0.1-f352f606f8-ced7bbbb64.zip"; sha512 = "ced7bbbb6433a5b684af581872afe0e1767e2d1146b2207ca0068a648fb5cab9d898495d1ac0583524faaf24ca98176a7d9876363097c2d14fee6dd324f3a1ab"; };
"nwsapi@npm:2.2.2" = { filename = "nwsapi-npm-2.2.2-b77040326c-4376910629.zip"; sha512 = "43769106292bc95f776756ca2f3513dab7b4d506a97c67baec32406447841a35f65f29c1f95ab5d42785210fd41668beed33ca16fa058780be43b101ad73e205"; };
"symbol-tree@npm:3.2.4" = { filename = "symbol-tree-npm-3.2.4-fe70cdb75b-6e8fc7e148.zip"; sha512 = "6e8fc7e1486b8b54bea91199d9535bb72f10842e40c79e882fc94fb7b14b89866adf2fd79efa5ebb5b658bc07fb459ccce5ac0e99ef3d72f474e74aaf284029d"; };
"webidl-conversions@npm:7.0.0" = { filename = "webidl-conversions-npm-7.0.0-e8c8e30c68-f05588567a.zip"; sha512 = "f05588567a2a76428515333eff87200fae6c83c3948a7482ebb109562971e77ef6dc49749afa58abb993391227c5697b3ecca52018793e0cb4620a48f10bd21b"; };
"whatwg-mimetype@npm:3.0.0" = { filename = "whatwg-mimetype-npm-3.0.0-5b617710c1-ce08bbb36b.zip"; sha512 = "ce08bbb36b6aaf64f3a84da89707e3e6a31e5ab1c1a2379fd68df79ba712a4ab090904f0b50e6693b0dafc8e6343a6157e40bf18fdffd26e513cf95ee2a59824"; };
"ws@npm:8.8.1" = { filename = "ws-npm-8.8.1-955e8c9f58-2152cf862c.zip"; sha512 = "2152cf862cae0693f3775bc688a6afb2e989d19d626d215e70f5fcd8eb55b1c3b0d3a6a4052905ec320e2d7734e20aeedbf9744496d62f15a26ad79cf4cf7dae"; };
"xml-name-validator@npm:4.0.0" = { filename = "xml-name-validator-npm-4.0.0-0857c21729-af100b79c2.zip"; sha512 = "af100b79c29804f05fa35aa3683e29a321db9b9685d5e5febda3fa1e40f13f85abc40f45a6b2bf7bee33f68a1dc5e8eaef4cec100a304a9db565e6061d4cb5ad"; };
"cssstyle@npm:2.3.0" = { filename = "cssstyle-npm-2.3.0-b5d112c450-5f05e6fd2e.zip"; sha512 = "5f05e6fd2e3df0b44695c2f08b9ef38b011862b274e320665176467c0725e44a53e341bc4959a41176e83b66064ab786262e7380fd1cabeae6efee0d255bb4e3"; };
"domexception@npm:4.0.0" = { filename = "domexception-npm-4.0.0-5093673f9b-ddbc1268ed.zip"; sha512 = "ddbc1268edf33a8ba02ccc596735ede80375ee0cf124b30d2f05df5b464ba78ef4f49889b6391df4a04954e63d42d5631c7fcf8b1c4f12bc531252977a5f13d5"; };
"html-encoding-sniffer@npm:3.0.0" = { filename = "html-encoding-sniffer-npm-3.0.0-daac3dfe41-8d806aa004.zip"; sha512 = "8d806aa00487e279e5ccb573366a951a9f68f65c90298eac9c3a2b440a7ffe46615aff2995a2f61c6746c639234e6179a97e18ca5ccbbf93d3725ef2099a4502"; };
"saxes@npm:6.0.0" = { filename = "saxes-npm-6.0.0-31558949f5-d3fa3e2aaf.zip"; sha512 = "d3fa3e2aaf6c65ed52ee993aff1891fc47d5e47d515164b5449cbf5da2cbdc396137e55590472e64c5c436c14ae64a8a03c29b9e7389fc6f14035cf4e982ef3b"; };
"w3c-hr-time@npm:1.0.2" = { filename = "w3c-hr-time-npm-1.0.2-87f88e51d9-ec3c2dacbf.zip"; sha512 = "ec3c2dacbf8050d917bbf89537a101a08c2e333b4c19155f7d3bedde43529d4339db6b3d049d9610789cb915f9515f8be037e0c54c079e9d4735c50b37ed52b9"; };
"w3c-xmlserializer@npm:3.0.0" = { filename = "w3c-xmlserializer-npm-3.0.0-3419fc8f05-0af8589942.zip"; sha512 = "0af8589942eeb11c9fe29eb31a1a09f3d5dd136aea53a9848dfbabff79ac0dd26fe13eb54d330d5555fe27bb50b28dca0715e09f9cc2bfa7670ccc8b7f919ca2"; };
"whatwg-encoding@npm:2.0.0" = { filename = "whatwg-encoding-npm-2.0.0-d7451f51b4-7087810c41.zip"; sha512 = "7087810c410aa9b689cbd6af8773341a53cdc1f3aae2a882c163bd5522ec8ca4cdfc269aef417a5792f411807d5d77d50df4c24e3abb00bb60192858a40cc675"; };
"graceful-fs@npm:4.2.10" = { filename = "graceful-fs-npm-4.2.10-79c70989ca-3f109d70ae.zip"; sha512 = "3f109d70ae123951905d85032ebeae3c2a5a7a997430df00ea30df0e3a6c60cf6689b109654d6fdacd28810a053348c4d14642da1d075049e6be1ba5216218da"; };
"universalify@npm:0.1.2" = { filename = "universalify-npm-0.1.2-9b22d31d2d-40cdc60f6e.zip"; sha512 = "40cdc60f6e61070fe658ca36016a8f4ec216b29bf04a55dce14e3710cc84c7448538ef4dad3728d0bfe29975ccd7bfb5f414c45e7b78883567fb31b246f02dff"; };
"acorn-globals@npm:6.0.0" = { filename = "acorn-globals-npm-6.0.0-acbec28ad5-72d95e5b5e.zip"; sha512 = "72d95e5b5e585f9acd019b993ab8bbba68bb3cbc9d9b5c1ebb3c2f1fe5981f11deababfb4949f48e6262f9c57878837f5958c0cca396f81023814680ca878042"; };
"whatwg-url@npm:11.0.0" = { filename = "whatwg-url-npm-11.0.0-073529d93a-ed4826aaa5.zip"; sha512 = "ed4826aaa57e66bb3488a4b25c9cd476c46ba96052747388b5801f137dd740b73fde91ad207d96baf9f17fbcc80fc1a477ad65181b5eb5fa718d27c69501d7af"; };
"jsonfile@npm:4.0.0" = { filename = "jsonfile-npm-4.0.0-10ce3aea15-6447d6224f.zip"; sha512 = "6447d6224f0d31623eef9b51185af03ac328a7553efcee30fa423d98a9e276ca08db87d71e17f2310b0263fd3ffa6c2a90a6308367f661dc21580f9469897c9e"; };
"data-urls@npm:3.0.2" = { filename = "data-urls-npm-3.0.2-c8b2050319-033fc3dd0f.zip"; sha512 = "033fc3dd0fba6d24bc9a024ddcf9923691dd24f90a3d26f6545d6a2f71ec6956f93462f2cdf2183cc46f10dc01ed3bcb36731a8208456eb1a08147e571fe2a76"; };
"http-proxy-agent@npm:5.0.0" = { filename = "http-proxy-agent-npm-5.0.0-7f1f121b83-e2ee1ff165.zip"; sha512 = "e2ee1ff1656a131953839b2a19cd1f3a52d97c25ba87bd2559af6ae87114abf60971e498021f9b73f9fd78aea8876d1fb0d4656aac8a03c6caa9fc175f22b786"; };
"cssom@npm:0.3.8" = { filename = "cssom-npm-0.3.8-a9291d36ff-24beb3087c.zip"; sha512 = "24beb3087c76c0d52dd458be9ee1fbc80ac771478a9baef35dd258cdeb527c68eb43204dd439692bb2b1ae5272fa5f2946d10946edab0d04f1078f85e06bc7f6"; };
"escodegen@npm:2.0.0" = { filename = "escodegen-npm-2.0.0-6450b02925-5aa6b2966f.zip"; sha512 = "5aa6b2966fafe0545e4e77936300cc94ad57cfe4dc4ebff9950492eaba83eef634503f12d7e3cbd644ecc1bab388ad0e92b06fd32222c9281a75d1cf02ec6cef"; };
"xmlchars@npm:2.2.0" = { filename = "xmlchars-npm-2.2.0-8b78f0f5e4-8c70ac9407.zip"; sha512 = "8c70ac94070ccca03f47a81fcce3b271bd1f37a591bf5424e787ae313fcb9c212f5f6786e1fa82076a2c632c0141552babcd85698c437506dfa6ae2d58723062"; };
"browser-process-hrtime@npm:1.0.0" = { filename = "browser-process-hrtime-npm-1.0.0-db700805c2-e30f868cdb.zip"; sha512 = "e30f868cdb770b1201afb714ad1575dd86366b6e861900884665fb627109b3cc757c40067d3bfee1ff2a29c835257ea30725a8018a9afd02ac1c24b408b1e45f"; };
"acorn-walk@npm:7.2.0" = { filename = "acorn-walk-npm-7.2.0-5f8b515308-9252158a79.zip"; sha512 = "9252158a79b9d92f1bc0dd6acc0fcfb87a67339e84bcc301bb33d6078936d27e35d606b4d35626d2962cd43c256d6f27717e70cbe15c04fff999ab0b2260b21f"; };
"acorn@npm:7.4.1" = { filename = "acorn-npm-7.4.1-f450b4646c-1860f23c21.zip"; sha512 = "1860f23c2107c910c6177b7b7be71be350db9e1080d814493fae143ae37605189504152d1ba8743ba3178d0b37269ce1ffc42b101547fdc1827078f82671e407"; };
"iconv-lite@npm:0.6.3" = { filename = "iconv-lite-npm-0.6.3-24b8aae27e-3f60d47a5c.zip"; sha512 = "3f60d47a5c8fc3313317edfd29a00a692cc87a19cac0159e2ce711d0ebc9019064108323b5e493625e25594f11c6236647d8e256fbe7a58f4a3b33b89e6d30bf"; };
"@tootallnate/once@npm:2.0.0" = { filename = "@tootallnate-once-npm-2.0.0-e36cf4f140-ad87447820.zip"; sha512 = "ad87447820dd3f24825d2d947ebc03072b20a42bfc96cbafec16bff8bbda6c1a81fcb0be56d5b21968560c5359a0af4038a68ba150c3e1694fe4c109a063bed8"; };
"tr46@npm:3.0.0" = { filename = "tr46-npm-3.0.0-e1ae1ea7c9-44c3cc6767.zip"; sha512 = "44c3cc6767fb800490e6e9fd64fd49041aa4e49e1f6a012b34a75de739cc9ed3a6405296072c1df8b6389ae139c5e7c6496f659cfe13a04a4bff3a1422981270"; };
"esprima@npm:4.0.1" = { filename = "esprima-npm-4.0.1-1084e98778-b45bc805a6.zip"; sha512 = "b45bc805a613dbea2835278c306b91aff6173c8d034223fa81498c77dcbce3b2931bf6006db816f62eacd9fd4ea975dfd85a5b7f3c6402cfd050d4ca3c13a628"; };
"estraverse@npm:5.3.0" = { filename = "estraverse-npm-5.3.0-03284f8f63-072780882d.zip"; sha512 = "072780882dc8416ad144f8fe199628d2b3e7bbc9989d9ed43795d2c90309a2047e6bc5979d7e2322a341163d22cfad9e21f4110597fe487519697389497e4e2b"; };
"esutils@npm:2.0.3" = { filename = "esutils-npm-2.0.3-f865beafd5-22b5b08f74.zip"; sha512 = "22b5b08f74737379a840b8ed2036a5fb35826c709ab000683b092d9054e5c2a82c27818f12604bfc2a9a76b90b6834ef081edbc1c7ae30d1627012e067c6ec87"; };
"source-map@npm:0.6.1" = { filename = "source-map-npm-0.6.1-1a3621db16-59ce8640cf.zip"; sha512 = "59ce8640cf3f3124f64ac289012c2b8bd377c238e316fb323ea22fbfe83da07d81e000071d7242cad7a23cd91c7de98e4df8830ec3f133cb6133a5f6e9f67bc2"; };
"optionator@npm:0.8.3" = { filename = "optionator-npm-0.8.3-bc555bc5b7-b8695ddf3d.zip"; sha512 = "b8695ddf3d593203e25ab0900e265d860038486c943ff8b774f596a310f8ceebdb30c6832407a8198ba3ec9debe1abe1f51d4aad94843612db3b76d690c61d34"; };
"deep-is@npm:0.1.4" = { filename = "deep-is-npm-0.1.4-88938b5a67-edb65dd0d7.zip"; sha512 = "edb65dd0d7d1b9c40b2f50219aef30e116cedd6fc79290e740972c132c09106d2e80aa0bc8826673dd5a00222d4179c84b36a790eef63a4c4bca75a37ef90804"; };
"fast-levenshtein@npm:2.0.6" = { filename = "fast-levenshtein-npm-2.0.6-fcd74b8df5-92cfec0a8d.zip"; sha512 = "92cfec0a8dfafd9c7a15fba8f2cc29cd0b62b85f056d99ce448bbcd9f708e18ab2764bda4dd5158364f4145a7c72788538994f0d1787b956ef0d1062b0f7c24c"; };
"prelude-ls@npm:1.1.2" = { filename = "prelude-ls-npm-1.1.2-a0daac0886-c4867c8748.zip"; sha512 = "c4867c87488e4a0c233e158e4d0d5565b609b105d75e4c05dc760840475f06b731332eb93cc8c9cecb840aa8ec323ca3c9a56ad7820ad2e63f0261dadcb154e4"; };
"word-wrap@npm:1.2.3" = { filename = "word-wrap-npm-1.2.3-7fb15ab002-30b48f91fc.zip"; sha512 = "30b48f91fcf12106ed3186ae4fa86a6a1842416df425be7b60485de14bec665a54a68e4b5156647dec3a70f25e84d270ca8bc8cd23182ed095f5c7206a938c1f"; };
"type-check@npm:0.3.2" = { filename = "type-check-npm-0.3.2-a4a38bb0b6-dd3b149564.zip"; sha512 = "dd3b1495642731bc0e1fc40abe5e977e0263005551ac83342ecb6f4f89551d106b368ec32ad3fb2da19b3bd7b2d1f64330da2ea9176d8ddbfe389fb286eb5124"; };
"levn@npm:0.3.0" = { filename = "levn-npm-0.3.0-48d774b1c2-0d084a5242.zip"; sha512 = "0d084a524231a8246bb10fec48cdbb35282099f6954838604f3c7fc66f2e16fa66fd9cc2f3f20a541a113c4dafdf181e822c887c8a319c9195444e6c64ac395e"; };
};

in optionalOverride overrideAttrs project
